In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv('passwords.csv',',',error_bad_lines=False,engine='python')
df.head()

Skipping line 2810: Expected 2 fields in line 2810, saw 5
Skipping line 4641: Expected 2 fields in line 4641, saw 5
Skipping line 7171: Expected 2 fields in line 7171, saw 5
Skipping line 11220: Expected 2 fields in line 11220, saw 5
Skipping line 13809: Expected 2 fields in line 13809, saw 5
Skipping line 14132: Expected 2 fields in line 14132, saw 5
Skipping line 14293: Expected 2 fields in line 14293, saw 5
Skipping line 14865: Expected 2 fields in line 14865, saw 5
Skipping line 17419: Expected 2 fields in line 17419, saw 5
Skipping line 22801: Expected 2 fields in line 22801, saw 5
Skipping line 25001: Expected 2 fields in line 25001, saw 5
Skipping line 26603: Expected 2 fields in line 26603, saw 5
Skipping line 26742: Expected 2 fields in line 26742, saw 5
Skipping line 29702: Expected 2 fields in line 29702, saw 5
Skipping line 32767: Expected 2 fields in line 32767, saw 5
Skipping line 32878: Expected 2 fields in line 32878, saw 5
Skipping line 35643: Expected 2 fields in line

password  strength
0     kzde5577         1
1     kino3434         1
2    visi7k1yr         1
3     megzy123         1
4  lamborghin1         1

In [4]:
len(df)

669640

In [5]:
df['strength'].unique()

array([1, 2, 0], dtype=int64)

In [6]:
%%time
df.isna().sum()

Wall time: 36.9 ms


password    1
strength    0
dtype: int64

In [7]:
df.dropna(inplace=True)
df.isna().sum()

password    0
strength    0
dtype: int64

In [8]:
df['strength'].value_counts()

1    496801
0     89701
2     83137
Name: strength, dtype: int64

In [9]:
import random
password_tuple = np.array(df)
random.shuffle(password_tuple)

In [10]:
def password_divide(password):
    character=[]
    for i in password:
        character.append(i)
    return character

### Transforming passwords using TFIDF

In [12]:
%%timeit
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer(tokenizer=password_divide)

x=[labels[0] for labels in password_tuple]
y=[labels[1] for labels in password_tuple]

X=vectorizer.fit_transform(x)

5.76 s ± 65.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2, random_state = 12)

### Creating Random Forest model

In [12]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(random_state = 12)
rfc.fit(X_train,y_train)

RandomForestClassifier(random_state=12)

#### Accuracy

In [13]:
rfc.score(X_test, y_test)

0.9852607371124783

#### Precision score

In [14]:
from sklearn.metrics import precision_score
predictions = rfc.predict(X_test)
precision_score(y_test, predictions, average = None)

array([0.98619632, 0.98453342, 0.98881197])

In [20]:
pass_array = np.array(['1234'])
pass_transformed=vectorizer.transform(pass_array)
rfc.predict(pass_transformed)

array([1])

#### Dictionaries for password genereator

In [21]:
alphabet_low = [ 'a', 'ą', 'b', 'c', 'ć', 'd', 'e', 'ę', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'ł', 'm', 'n', 'ń', 'o', 'ó', 'p', 'q', 'r', 's', 'ś', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'ź', 'ż']
alphabet_upp = []
for i in range(len(alphabet_low)):
    alphabet_upp.append(str(alphabet_low[i].upper()))
numbers = ['0','1','2','3','4','5','6','7','8','9']
symbols = [ '~','`','!', '@','#','$','%','^','&','*','(',')','_','-','+','=','{','[','}',']','|','\',',':',';','"',"'",'<','>','.','?','/']
all_symbols = alphabet_low + alphabet_upp + numbers + symbols
random.shuffle(all_symbols)
all_symbols

['v',
 'H',
 'J',
 '(',
 '&',
 'ż',
 'a',
 'T',
 '^',
 'K',
 'q',
 '9',
 '"',
 'Ć',
 '4',
 ')',
 'I',
 'U',
 '=',
 'F',
 'ś',
 'x',
 ':',
 '~',
 'l',
 'ą',
 '[',
 'V',
 'X',
 '`',
 "',",
 'c',
 'w',
 '*',
 'd',
 '1',
 '+',
 'L',
 'Ó',
 'h',
 'f',
 'n',
 'Ą',
 '3',
 'Ł',
 'g',
 '7',
 'R',
 'B',
 '>',
 '%',
 '8',
 'p',
 '{',
 'Ś',
 'ń',
 '2',
 'S',
 'Q',
 '@',
 'D',
 'ó',
 'Ź',
 '_',
 '5',
 'M',
 'ę',
 'W',
 '|',
 'Ę',
 'O',
 ']',
 '$',
 ';',
 '?',
 '.',
 'Y',
 '0',
 'y',
 'ź',
 '-',
 'Ż',
 'ć',
 'i',
 '6',
 '!',
 's',
 'C',
 'o',
 'e',
 '/',
 'N',
 'A',
 "'",
 'Z',
 'E',
 'm',
 '#',
 't',
 'ł',
 'r',
 'b',
 'G',
 '}',
 'Ń',
 'z',
 'k',
 'u',
 'P',
 '<',
 'j']

In [22]:
def password_generator(length=3):
    if length < 3:
        print("Length of the password is too short")
    elif length == 3:
        password_list = []
        password_list.append( random.choice(alphabet_upp))
        password_list.append( random.choice(numbers))
        password_list.append( random.choice(symbols))
        random.shuffle(password_list)
        random.shuffle(password_list)
        password = ''.join(password_list)
    else:
        password_list = []
        password_list.append( random.choice(alphabet_upp))
        password_list.append( random.choice(numbers))
        password_list.append( random.choice(symbols))
        random.shuffle(password_list)
        for n in range(length-3):
            password_list.append(random.choice(all_symbols))
        random.shuffle(password_list)
        password = ''.join(password_list)
        return password

#### Clasification of 1000 random generated passwords using model created above

In [24]:
predictions = []
for n in range(1000):
    password = password_generator(7)
    pass_array = np.array([password])
    password_transformed=vectorizer.transform(pass_array)
    pred_strength = rfc.predict(password_transformed)
    predictions.append(pred_strength)

In [31]:
zeros = []
ones = []
twos = []
for n in predictions:
    if n == 0:
        zeros.append(n)
    elif n == 1:
        ones.append(n)
    else:
        twos.append(n)

In [38]:
print("0: " + str(len(zeros)),"1: " + str(len(ones)), "2: " + str(len(twos)))

1: 106 2: 777 3: 117


#### Clasification of 10000 random generated passwords using model created above

In [39]:
predictions = []
for n in range(10000):
    password = password_generator(7)
    pass_array = np.array([password])
    password_transformed=vectorizer.transform(pass_array)
    pred_strength = rfc.predict(password_transformed)
    predictions.append(pred_strength)
    
zeros = []
ones = []
twos = []
for n in predictions:
    if n == 0:
        zeros.append(n)
    elif n == 1:
        ones.append(n)
    else:
        twos.append(n)

print("0: " + str(len(zeros)),"1: " + str(len(ones)), "2: " + str(len(twos)))

1: 1083 2: 7849 3: 1068


#### Clasification of 1000 random generated passwords with different lengths

In [46]:
for t in range(3,16):
    predictions = []
    for k in range(1000):
        password = password_generator(7)
        pass_array = np.array([password])
        password_transformed=vectorizer.transform(pass_array)
        pred_strength = rfc.predict(password_transformed)
        predictions.append(pred_strength)
        
    zeros = []
    ones = []
    twos = []
    for n in predictions:
        if n == 0:
            zeros.append(n)
        elif n == 1:
            ones.append(n)
        else:
            twos.append(n)
    print('Results for length = ' + str(t))
    print("0: " + str(len(zeros)),"1: " + str(len(ones)), "2: " + str(len(twos)))  

Results for length = 3
0: 103 1: 789 2: 108
Results for length = 4
0: 100 1: 790 2: 110
Results for length = 5
0: 107 1: 776 2: 117
Results for length = 6
0: 118 1: 784 2: 98
Results for length = 7
0: 105 1: 787 2: 108
Results for length = 8
0: 108 1: 801 2: 91
Results for length = 9
0: 127 1: 754 2: 119
Results for length = 10
0: 96 1: 783 2: 121
Results for length = 11
0: 116 1: 786 2: 98
Results for length = 12
0: 85 1: 809 2: 106
Results for length = 13
0: 112 1: 788 2: 100
Results for length = 14
0: 96 1: 795 2: 109
Results for length = 15
0: 118 1: 769 2: 113


In [58]:
def strong_password_generator(length):
    status = 0
    num_iter = 0
    while status != 2:
        num_iter += 1
        password = password_generator(length)
        dt = np.array([password])
        pred=vectorizer.transform(dt)
        pass_strength = rfc.predict(pred)
        status = pass_strength
    return num_iter

In [59]:
strong_password_generator(7)

6

In [60]:
iterations = []
for n in range(1000):
    iterations.append(strong_password_generator(7))

In [66]:
sum = 0
for n in iterations:
    sum = sum + n
    
sum/len(iterations)

8.952

#### Experiment of checking how many iterations does random password generator need to generate password with the highest strength

In [68]:
for t in range(3,16):
    iterations = []
    for n in range(1000):
        iterations.append(strong_password_generator(7))
    sum = 0
    for k in iterations:
        sum = sum + k
    print('Average number of iterations for length = ' + str(t))
    print(str(sum/len(iterations)))

Average number of iterations for length = 3
8.767
Average number of iterations for length = 4
8.748
Average number of iterations for length = 5
8.605
Average number of iterations for length = 6
8.775
Average number of iterations for length = 7
9.336
Average number of iterations for length = 8
8.989
Average number of iterations for length = 9
9.482
Average number of iterations for length = 10
8.748
Average number of iterations for length = 11
8.786
Average number of iterations for length = 12
8.483
Average number of iterations for length = 13
9.352
Average number of iterations for length = 14
8.941
Average number of iterations for length = 15
9.287
